import * as THREE from "three";

/**
 * InterestMap tracks "heat" in the world grid.
 * Heat is generated by activity (player movement, conversations, items dropped).
 * Heat decays over time.
 */
export class InterestMap {
  private static instance: InterestMap;
  
  private gridSize: number = 100; // 100x100 grid
  private resolution: number = 2; // 2 meters per cell
  private offset: number = 100; // Offset to handle negative coordinates
  
  private grid: Float32Array;
  private lastDecayTime: number = Date.now();
  /** Indices with heat > 0 — sparse decay avoids scanning 10k cells every frame */
  private activeIndices = new Set<number>();

  private constructor() {
    this.grid = new Float32Array(this.gridSize * this.gridSize);
  }

  public static getInstance(): InterestMap {
    if (!InterestMap.instance) {
      InterestMap.instance = new InterestMap();
    }
    return InterestMap.instance;
  }

  private getIndex(x: number, z: number): number {
    const gx = Math.floor((x + this.offset) / this.resolution);
    const gz = Math.floor((z + this.offset) / this.resolution);
    
    if (gx < 0 || gx >= this.gridSize || gz < 0 || gz >= this.gridSize) return -1;
    return gz * this.gridSize + gx;
  }

  public addHeat(position: THREE.Vector3, amount: number) {
    const idx = this.getIndex(position.x, position.z);
    if (idx !== -1) {
      this.grid[idx] = Math.min(10, this.grid[idx] + amount);
      if (this.grid[idx] > 0) this.activeIndices.add(idx);
    }
  }

  public getHeat(position: THREE.Vector3): number {
    const idx = this.getIndex(position.x, position.z);
    if (idx === -1) return 0;
    return this.grid[idx];
  }

  public update(deltaSec: number) {
    const decayRate = 0.2; // Heat units per second
    const amount = decayRate * deltaSec;
    if (this.activeIndices.size === 0) return;
    const toRemove: number[] = [];
    for (const i of this.activeIndices) {
      const next = Math.max(0, this.grid[i] - amount);
      this.grid[i] = next;
      if (next <= 0) toRemove.push(i);
    }
    for (const i of toRemove) this.activeIndices.delete(i);
  }

  /**
   * Finds the cell with the highest heat within a radius.
   * Returns a Vector3 for that cell's center, or null if no heat found.
   */
  public getInterestingSpot(position: THREE.Vector3, radius: number): THREE.Vector3 | null {
    let bestIdx = -1;
    let maxHeat = 0.1; // Threshold to care
    
    const gxCenter = (position.x + this.offset) / this.resolution;
    const gzCenter = (position.z + this.offset) / this.resolution;
    const gRadius = radius / this.resolution;

    for (let gz = Math.floor(gzCenter - gRadius); gz <= Math.ceil(gzCenter + gRadius); gz++) {
      for (let gx = Math.floor(gxCenter - gRadius); gx <= Math.ceil(gxCenter + gRadius); gx++) {
        if (gx < 0 || gx >= this.gridSize || gz < 0 || gz >= this.gridSize) continue;
        
        const idx = gz * this.gridSize + gx;
        if (this.grid[idx] > maxHeat) {
          maxHeat = this.grid[idx];
          bestIdx = idx;
        }
      }
    }

    if (bestIdx !== -1) {
      const gz = Math.floor(bestIdx / this.gridSize);
      const gx = bestIdx % this.gridSize;
      return new THREE.Vector3(
        gx * this.resolution - this.offset + this.resolution / 2,
        position.y,
        gz * this.resolution - this.offset + this.resolution / 2
      );
    }

    return null;
  }

  /**
   * Cell center of the strongest heat within `maxRadius` (world units), if above `minHeat`.
   */
  public getNearestHotSpot(
    position: THREE.Vector3,
    maxRadius: number,
    minHeat = 0.12,
  ): THREE.Vector3 | null {
    let bestIdx = -1;
    let maxHeat = minHeat;

    const gxCenter = (position.x + this.offset) / this.resolution;
    const gzCenter = (position.z + this.offset) / this.resolution;
    const gRadius = maxRadius / this.resolution;

    for (
      let gz = Math.floor(gzCenter - gRadius);
      gz <= Math.ceil(gzCenter + gRadius);
      gz++
    ) {
      for (
        let gx = Math.floor(gxCenter - gRadius);
        gx <= Math.ceil(gxCenter + gRadius);
        gx++
      ) {
        if (gx < 0 || gx >= this.gridSize || gz < 0 || gz >= this.gridSize)
          continue;

        const wx = gx * this.resolution - this.offset + this.resolution / 2;
        const wz = gz * this.resolution - this.offset + this.resolution / 2;
        const dist = Math.hypot(wx - position.x, wz - position.z);
        if (dist > maxRadius) continue;

        const idx = gz * this.gridSize + gx;
        if (this.grid[idx] > maxHeat) {
          maxHeat = this.grid[idx];
          bestIdx = idx;
        }
      }
    }

    if (bestIdx !== -1) {
      const gz = Math.floor(bestIdx / this.gridSize);
      const gx = bestIdx % this.gridSize;
      return new THREE.Vector3(
        gx * this.resolution - this.offset + this.resolution / 2,
        position.y,
        gz * this.resolution - this.offset + this.resolution / 2,
      );
    }
    return null;
  }
}
